"""create agent_events table

Revision ID: fb0df2b9147c
Revises: 
Create Date: 2025-12-06 13:47:20.158538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb0df2b9147c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_events_agent_id'), 'agent_events', ['agent_id'], unique=False)
    # ### end Alembic commands ###

    # Create pg_notify trigger function and trigger
    op.execute("""
        CREATE OR REPLACE FUNCTION notify_agent_event() RETURNS trigger AS $$
        BEGIN
            PERFORM pg_notify('agent_events', jsonb_build_object(
                'id', NEW.id::text,
                'agent_id', NEW.agent_id,
                'event_type', NEW.event_type,
                'payload', NEW.payload,
                'created_at', NEW.created_at::text
            )::text);
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)

    op.execute("""
        CREATE TRIGGER agent_event_notify
            AFTER INSERT ON agent_events
            FOR EACH ROW EXECUTE FUNCTION notify_agent_event();
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # Drop trigger and function first
    op.execute("DROP TRIGGER IF EXISTS agent_event_notify ON agent_events")
    op.execute("DROP FUNCTION IF EXISTS notify_agent_event")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_events_agent_id'), table_name='agent_events')
    op.drop_table('agent_events')
    # ### end Alembic commands ###
