# Makefile for kairix-core module

# Module-specific variables
MODULE_NAME := kairix-core
MODULE_PATH := $(shell pwd)

# Include common targets
include ../make/common.mk

# Module-specific targets can be added here

# Override the help target to use module-help
.PHONY: help
help: module-help

.DEFAULT_GOAL := help