[req]
distinguished_name = req_distinguished_name
x509_extensions = v3_req
prompt = no

[req_distinguished_name]
C = US
ST = State
L = City
O = Kairix Dev
CN = localhost

[v3_req]
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names

[alt_names]
DNS.1 = localhost
DNS.2 = *.localhost
DNS.3 = kairix.local
IP.1 = 127.0.0.1
IP.2 = 192.168.87.20
IP.3 = 100.107.199.10
IP.4 = 169.254.61.93
IP.5 = ::1