[providers]
[[ollama_local]]
provider_type = "openai"
base_url = "http://localhost:11434/v1"
uses_responses = false
default_model=""

[[ollama_remotel]]
provider_type = "openai"
base_url = "http://localhost:11434/v1"
uses_responses = false
default_model=""

[[ollama_local]]
provider_type = "openai"
base_url = "http://localhost:11434/v1"
uses_responses = false
default_model=""
