# Define data models first
from typing import Literal, Optional

from pydantic import BaseModel, ConfigDict


class Subject(BaseModel):
    model_config = ConfigDict(strict=False)
    type: Literal[
        # Core Entity Types
        "person",
        "organization",
        "location",
        "event",
        "concept",
        "object",
        "document",
        "time_period",
        # People & Roles
        "role",
        "group",
        "team",
        "community",
        # Places
        "place",
        "facility",
        "region",
        "country",
        "city",
        # Abstract Concepts
        "idea",
        "theory",
        "principle",
        "belief",
        "value",
        "goal",
        "strategy",
        "method",
        "process",
        "system",
        "framework",
        "model",
        "pattern",
        # Knowledge & Information
        "topic",
        "field",
        "domain",
        "skill",
        "capability",
        "knowledge_area",
        # Activities & States
        "activity",
        "action",
        "task",
        "project",
        "initiative",
        "state",
        "condition",
        "situation",
        # Artifacts & Creations
        "product",
        "service",
        "technology",
        "tool",
        "resource",
        "asset",
        "work",
        "publication",
        "creation",
        # Relationships & Structures
        "relationship",
        "agreement",
        "contract",
        "rule",
        "policy",
        "standard",
        "requirement",
        # Measures & Attributes
        "metric",
        "measurement",
        "attribute",
        "property",
        "characteristic",
        "quality",
        # Problems & Solutions
        "problem",
        "challenge",
        "issue",
        "risk",
        "opportunity",
        "solution",
        "outcome",
        "result",
        # Temporal
        "moment",
        "duration",
        "milestone",
        "phase",
        "cycle",
        # Communication
        "message",
        "communication",
        "narrative",
        "argument",
        "question",
        "answer",
        # Economic
        "transaction",
        "exchange",
        "market",
        "economy",
        "industry",
        # Biological/Natural
        "organism",
        "species",
        "environment",
        "phenomenon",
        # Cultural/Social
        "culture",
        "tradition",
        "movement",
        "trend",
        # Technical/Digital
        "data",
        "information",
        "software",
        "hardware",
        "network",
        "platform",
        "interface",
        "component",
        "element",
    ]
    name: str

    def semantic_identifer(self):
        return f"{self.type}_{self.name}"


class Fact(BaseModel):
    model_config = ConfigDict(strict=False)
    s: Subject
    t: Subject
    relationship: Literal[
        "owns",
        "belongs_to",
        "manages",
        "created_by",
        "works_with",
        "reports_to",
        "collaborates_with",
        "mentored_by",
        "affiliated_with",
        "member_of",
        "performs",
        "engages_in",
        "executes",
        "initiates",
        "completes",
        "enables",
        "prevents",
        "follows",
        "precedes",
        "triggers",
        "results_in",
        "depends_on",
        "conflicts_with",
        "supports",
        "implements",
        "demonstrates",
        "exhibits",
        "possesses",
        "characterized_by",
        "embodies",
        "lacks",
        "develops",
        "strengthens",
        "weakens",
        "complements",
        "contradicts",
        "studies",
        "researches",
        "interested_in",
        "specializes_in",
        "expert_in",
        "learning",
        "teaches",
        "applies",
        "relates_to",
        "subset_of",
        "superset_of",
        "overlaps_with",
        "distinct_from",
        "fundamental_to",
        "derives_from",
        "evolves_into",
        "branches_from",
        "occurred_during",
        "happened_before",
        "happened_after",
        "concurrent_with",
        "caused_by",
        "led_to",
        "participated_in",
        "witnessed",
        "affected_by",
        "transformed_by",
        "catalyzed",
        "interrupted_by",
        "masters",
        "proficient_in",
        "familiar_with",
        "novice_at",
        "certified_in",
        "trained_in",
        "practices",
        "aims_to",
        "pursues",
        "seeks",
        "avoids",
        "prioritizes",
        "values",
        "committed_to",
        "motivated_by",
        "creates",
        "produces",
        "generates",
        "designs",
        "builds",
        "authors",
        "contributes_to",
        "maintains",
        "improves",
        "optimizes",
        "analyzes",
        "evaluates",
        "interprets",
        "questions",
        "explores",
        "investigates",
        "discovers",
        "realizes",
        "understands",
        "misunderstands",
        "communicates",
        "expresses",
        "explains",
        "describes",
        "documents",
        "presents",
        "shares",
        "discusses",
        "debates",
        "argues",
        "influences",
        "impacts",
        "shapes",
        "determines",
        "constrains",
        "liberates",
        "empowers",
        "limits",
        "enhances",
        "diminishes",
        "requires",
        "needs",
        "prefers",
        "suitable_for",
        "incompatible_with",
        "ready_for",
        "preparing_for",
        "transitioning_to",
        "greater_than",
        "less_than",
        "equal_to",
        "similar_to",
        "different_from",
        "comparable_to",
        "proportional_to",
        "inversely_related_to",
        "solves",
        "addresses",
        "mitigates",
        "complicates",
        "simplifies",
        "clarifies",
        "obscures",
        "contains",
        "composed_of",
        "integrates_with",
        "interfaces_with",
        "extends",
        "modifies",
        "replaces",
        "upgrades",
        "depends_upon",
        "independent_of",
    ]


class Extract(BaseModel):
    model_config = ConfigDict(strict=False)
    facts: Optional[list[Fact]]
